# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yongha Woo
email: dmg0793@snu.ac.kr
description: ""
twitter_username: ""
github_username: ""
minimal_mistakes_skin: default
search: true
powered_by: false

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name : "Yongha Woo"
  avatar : "/assets/images/bio-photo.jpg"
  bio : ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://dmg0793.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dmg0793"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dmg0793"
    - label: "Feed"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
